### ISSUE TITLE
[FEATURE] ASPNETCORE UI (MVC)

### ISSUE THREAD

**Issue by NicoCG** [hexiron/Azure.ActiveDirectory#2]
Hello @mkeymolen ,

Please could you add a ASPNETCORE MVC user interface sample where users have the ability to SignIn, SighUp, ResetPassword and Signout?

**Comment by mkeymolen** [comment]
@NicoCG i can do that, but you still need to configure some stuff in Azure Ad/B2c . i'll try to implement the feature and add some documentation

**Comment by NicoCG** [comment]
Hi @mkeymolen,

That would be great I excited to see this sample.

**Comment by NicoCG** [comment]
Hi @mkeymolen, Sorry to bother you but is there and ETA on this implementation on this sample. 
Do not want to sound needy haha just need it for a project 🙈

**Comment by mkeymolen** [comment]
> Hi @mkeymolen, Sorry to bother you but is there and ETA on this implementation on this sample.
> Do not want to sound needy haha just need it for a project 🙈

Sorry, very busy at the moment. I'll see what i can do asap

**Comment by NicoCG** [comment]
@mkeymolen Thank you, this means a lot to me.

**Comment by ghost** [comment]
Hi @mkeymolen,

I just want to confirm is this [sample](https://github.com/hexiron/Hexiron.AspNetCore.Authentication.AzureAdMixed/tree/master/samples/Hexiron.AspNetCore.Authentication.UiSample) related to this issues request?

If so may I suggest why not merge Library [A](https://github.com/hexiron/Hexiron.AspNetCore.Authentication.AzureAdMixed/tree/master/src/Hexiron.AspNetCore.Authentication.AzureAdMixed) with [B](https://github.com/hexiron/Hexiron.Azure.ActiveDirectory/tree/master/src/Hexiron.Azure.ActiveDirectory) so you have one library **Hexiron.Azure.ActiveDirectory** to maintain which caters for UI and API?

If not the merge suggestion then maybe rename the library **Hexiron.AspNetCore.Authentication.AzureAdMixed** to **Hexiron.Azure.ActiveDirectory.B2C** maybe?

**Comment by mkeymolen** [comment]
@nicotravassos i updated the READMES and added a HowTo in the wiki.
This library only contains the basics and the API connectors. The [Hexiron.AspNetCore.Authentication.AzureAdMixed](https://github.com/hexiron/Hexiron.AspNetCore.Authentication.AzureAdMixed) library contains extensions on the current Microsoft.AspNetCore.Authentication library that enables you to use both AzureAD and Azure AD B2C in the same host.
With the extensions in that library you can accept JWT tokens issued by either an Azure AD or Azure B2C tenant. It has a dependency on this library. So adding that nuget package also adds the nuget package of this library. 

However, i also added howTo's in the wiki and a UI sample (as you noted above) where i show how you can activate Azure AD B2C authentication. 
See [How to Authenticate with Azure AD B2C in AspNetCore](https://github.com/hexiron/Hexiron.AspNetCore.Authentication.AzureAdMixed/wiki/How-to-Authenticate-with-Azure-AD-B2C-in-AspNetCore)  

This should fix this feature request @NicoCG .
